/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_sai.h"
#include "fsl_clock.h"
#include "fsl_uart.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define I2S0_PERIPHERAL I2S0
/* I2S0 interrupt vector ID (number). */
#define I2S0_SERIAL_TX_IRQN I2S0_Tx_IRQn
/* I2S0 interrupt handler identifier. */
#define I2S0_SERIAL_TX_IRQHANDLER I2S0_Tx_IRQHandler
/* Master clock source frequency used for calculating the master clock divider, not available on all devices. */
#define I2S0_MCLK_SOURCE_CLOCK_HZ 120000000UL
/* Master clock value set by the user to the Master clock frequency item. */
#define I2S0_USER_MCLK_HZ 6144000UL
/* Bit clock source frequency used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define I2S0_TX_BCLK_SOURCE_CLOCK_HZ 6144000UL
/* Sample rate used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define I2S0_TX_SAMPLE_RATE 16000UL
/* Word width used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define I2S0_TX_WORD_WIDTH 16U
/* Number of words within frame used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define I2S0_TX_WORDS_PER_FRAME 2U
/* Definition of peripheral ID */
#define UART0_PERIPHERAL UART0
/* Definition of the clock source frequency */
#define UART0_CLOCK_SOURCE CLOCK_GetFreq(UART0_CLK_SRC)

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern sai_transceiver_t I2S0_Tx_config;
extern const uart_config_t UART0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
