/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (coord E10), U7[4]/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB17 (coord E9), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC1 (coord B11), J1[5]/U20[C5]/I2S_TXD
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2S_TXD_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2S_TXD_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_I2S_TXD_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTC6 (coord C8), J1[7]/LLWU_P10/FB_AD9/I2S0_MCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2S_MCLK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2S_MCLK_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_I2S_MCLK_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTE12 (coord G3), J1[1]/J37[3]/I2S_TX_BCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2S_TX_BCLK_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_I2S_TX_BCLK_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_I2S_TX_BCLK_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTE11 (coord G4), J1[3]/J38[3]/I2S_TX_WCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2S_TX_WCLK_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_I2S_TX_WCLK_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_I2S_TX_WCLK_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC10 (coord C7), J2[20]/U20[D8]/I2C1_SCL/DA7212_CLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2C1_SCL_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C1_SCL_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_I2C1_SCL_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTC11 (coord B7), J2[18]/U20[C9]/I2C1_SDA/DA7212_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2C1_SDA_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C1_SDA_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_I2C1_SDA_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/

